/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Arista;
import Modelo.Grafo;
import Modelo.Respuesta;
import Modelo.Vertice;

/**
 *
 * @author EDWIN
 */
public class Interfaz extends javax.swing.JFrame {

    private String LugarInicio;
    private String LugarMeta;
    /**
     * Creates new form Interfaz
     */
    String inicio;
    String meta;
    public Interfaz() {
        inicio="";
        meta="";
        
        initComponents();
        //nombre de la ventana
        
        this.setTitle("LUGARES TURISTICOS");
        //llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        INICIO = new javax.swing.JComboBox<>();
        META = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        label4 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        TERMINAL = new javax.swing.JTextArea();
        FONDO = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setToolTipText("");
        jPanel1.setFocusCycleRoot(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("LUGARES TURISTICOS"), jPanel1, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        Buscar.setText("BUSCAR");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        CANCELAR.setText(" CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        INICIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Plaza 14 de septiembre", "Universidad mayo de Sansimon", "Laguna Alalay", "Parque de la Familia", "Jardin Botanico", "Cristo de la Concordia", "Parque Mariscal Santa Cruz", "Coliseo de la Coronilla" }));
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });

        META.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Plaza 14 de septiembre", "Universidad mayo de Sansimon", "Laguna Alalay", "Parque de la Familia", "Jardin Botanico", "Cristo de la Concordia", "Parque Mariscal Santa Cruz", "Coliseo de la Coronilla" }));
        META.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METAActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(0, 51, 51));
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 0, 51));
        label1.setText(" INICIO");

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setEnabled(false);
        label2.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 102, 102));
        label2.setName(""); // NOI18N
        label2.setText("Busqueda en Profundidad");

        label3.setBackground(new java.awt.Color(0, 51, 51));
        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 0, 51));
        label3.setText(" META");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        label4.setForeground(new java.awt.Color(204, 0, 0));
        label4.setName(""); // NOI18N
        label4.setText("Inteligencia Artificial 2016");

        TERMINAL.setEditable(false);
        TERMINAL.setColumns(20);
        TERMINAL.setRows(5);
        jScrollPane2.setViewportView(TERMINAL);

        FONDO.setBackground(new java.awt.Color(102, 102, 255));
        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cochabamba.png"))); // NOI18N
        FONDO.setBorderPainted(false);
        FONDO.setFocusPainted(false);
        FONDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FONDOActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/lugaresTuristicos.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(META, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(INICIO, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))
                            .addComponent(jLayeredPane1))
                        .addGap(628, 628, 628))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(META, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FONDO))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jPanel1.getAccessibleContext().setAccessibleName("LUGARES TURISTICOS");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FONDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FONDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FONDOActionPerformed

    private void METAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METAActionPerformed
        LugarMeta=META.getSelectedItem().toString();
        // TODO add your handling code here:
         meta = String.valueOf(META.getSelectedIndex()).trim();
         System.out.println(META.getSelectedIndex());
    }//GEN-LAST:event_METAActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        LugarInicio=INICIO.getSelectedItem().toString();
        //System.out.println("item selected. " + INICIO.getSelectedItem().toString());
        inicio = String.valueOf(INICIO.getSelectedIndex()).trim();
         System.out.println(INICIO.getSelectedIndex());

    }//GEN-LAST:event_INICIOActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CANCELARActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        TERMINAL.setText("");
        TERMINAL.append( "    Terminal Funcionando con Exito!!"+"\n"+"\n");
        TERMINAL.append("Lugar Inicio:  "+LugarInicio+"\n"+"Lugar Final:  "+LugarMeta +"\n");
        
    //////////////////////////7
    Vertice v1 = new Vertice("1");    
        Vertice v2 = new Vertice("2");
        Vertice v3 = new Vertice("3");
        Vertice v4 = new Vertice("4");
        Vertice v5 = new Vertice("5");
        Vertice v6 = new Vertice("6");
        Vertice v7 = new Vertice("7");
        Vertice v8 = new Vertice("8");

        
        
        v1.insertarVecino(new Arista(v1, v2));
        v1.insertarVecino(new Arista(v1, v4));
        v1.insertarVecino(new Arista(v1, v5));
        v1.insertarVecino(new Arista(v1, v8));
        
        v1.addVerticeVecino(v2);
        v1.addVerticeVecino(v4);
        v1.addVerticeVecino(v5);
        v1.addVerticeVecino(v8);
        
        //v2.insertarVecino(new Arista(v1, v2));
         v2.insertarVecino(new Arista(v2, v1));
         v2.insertarVecino(new Arista(v2, v3));
         v2.insertarVecino(new Arista(v2, v5));
         v2.insertarVecino(new Arista(v2, v6));
        v2.addVerticeVecino(v1);
        v2.addVerticeVecino(v3);
        v2.addVerticeVecino(v5);
        v2.addVerticeVecino(v6);
        
        v3.insertarVecino(new Arista(v3, v2));
        v3.insertarVecino(new Arista(v3, v8));
        v3.addVerticeVecino(v2);
        v3.addVerticeVecino(v8);
        
        v4.insertarVecino(new Arista(v4, v1));
        v3.insertarVecino(new Arista(v4, v7));
        v4.addVerticeVecino(v1);
        v4.addVerticeVecino(v7);
        
        v5.insertarVecino(new Arista(v5, v1));
        v5.insertarVecino(new Arista(v5, v2));
        v5.addVerticeVecino(v1);
        v5.addVerticeVecino(v2);
        //v6.insertarVecino(new Arista(v5, v6));
        v6.addVerticeVecino(v2);
        
        v7.insertarVecino(new Arista(v7, v4));
        v7.insertarVecino(new Arista(v7, v8));
        v7.addVerticeVecino(v4);
        v7.addVerticeVecino(v8);
        //v8.insertarVecino(new Arista(v7, v8));
        v8.insertarVecino(new Arista(v8, v1));
        v8.insertarVecino(new Arista(v8, v3));
        v8.insertarVecino(new Arista(v8, v7));
        v8.addVerticeVecino(v1);
        v8.addVerticeVecino(v3);
        v8.addVerticeVecino(v7);
        
     // Grafo grafo = new Grafo();
      //System.out.println("tiempo Transcurrido: "+ " ms.");
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v1,v2);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v1,v3);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v1,v4);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v1,v5);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v1,v6);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v1,v7);}
       if(inicio.equals(v1.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v1,v8);}
       
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v2,v1);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v2,v3);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v2,v4);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v2,v5);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v2,v6);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v2,v7);}
       if(inicio.equals(v2.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v2,v8);}
       
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v3,v1);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v3,v2);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v3,v4);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v3,v5);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v3,v6);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v3,v7);}
       if(inicio.equals(v3.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v3,v8);}
       
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v4,v1);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v4,v2);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v4,v3);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v4,v5);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v4,v6);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v4,v7);}
       if(inicio.equals(v4.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v4,v8);}
       
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v5,v1);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v5,v2);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v5,v3);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v5,v4);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v5,v6);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v5,v7);}
       if(inicio.equals(v5.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v5,v8);}
       
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v6,v1);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v6,v2);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v6,v3);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v6,v4);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v6,v5);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v6,v7);}
       if(inicio.equals(v6.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v6,v8);}
       
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v7,v1);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v7,v2);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v7,v3);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v7,v4);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v7,v5);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v7,v6);}
       if(inicio.equals(v7.getEtiqueta()) && meta.equals(v8.getEtiqueta())){ruteo(v7,v8);}
       
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v1.getEtiqueta())){ruteo(v8,v1);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v2.getEtiqueta())){ruteo(v8,v2);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v3.getEtiqueta())){ruteo(v8,v3);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v4.getEtiqueta())){ruteo(v8,v4);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v5.getEtiqueta())){ruteo(v8,v5);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v6.getEtiqueta())){ruteo(v8,v6);}
       if(inicio.equals(v8.getEtiqueta()) && meta.equals(v7.getEtiqueta())){ruteo(v8,v7);} 
    }
       
       private void ruteo(Vertice vi,Vertice vf){
        Grafo grafo = new Grafo();
           Respuesta res = grafo.Buscar(vi, vf);
        System.out.print("Ruta Solucion: ");
        TERMINAL.append("Ruta Solucion:  ");
         for (String imprime : res.getrutas()) {
            System.out.println(imprime + ". ");
            TERMINAL.append(imprime + " - ");
         }
           System.out.println("");
           TERMINAL.append("\n");
       
           TERMINAL.append("Nodos Visitados:  "+ res.getNodosVisitados()+"\n");
           TERMINAL.append("tiempo Transcurrido:  "+ res.getTiempoTrans()+ " ms."+"\n");
        
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//<editor-fold defaultstate="collapsed" desc="comment">
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//</editor-fold>
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton FONDO;
    private javax.swing.JComboBox<String> INICIO;
    private javax.swing.JComboBox<String> META;
    private javax.swing.JTextArea TERMINAL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
